[package]
name = "clap_complete_command"
version = "0.3.2"
edition = "2021"

description = "Reduces boilerplate for adding a shell completion command to Clap"
repository = "https://github.com/nihaals/clap-complete-command"
documentation = "https://docs.rs/clap_complete_command"
license = "MIT"
keywords = ["clap", "cli", "completion"]
categories = ["command-line-interface"]

[dependencies]
clap = "3"
clap_complete = "3"
clap_complete_fig = "3"

[dev-dependencies]
clap = { version = "3", features = ["derive"] }
